#! /usr/bin/env bash

git pull
ur="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
$ur/pullall

source .venv/bin/activate
yarn install
pip install -r requirements.txt

yarn parcel build client/index.html --public-url /static/
./manage.py collectstatic --no-input
./manage.py migrate

$ur/restart