#! /usr/bin/env bash

set -e

YAPF_ARGS="-d"
if [[ $1 == "--fix" ]];then
    YAPS_ARGS="-i"
fi

if [ -f ".eslintrc" ]; then
    yarn lint $1
fi

if [ -f ".yapfignore" ]; then
    source .venv/bin/activate
    yapf . -r $YAPF_ARGS
fi