#! /usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
_PWD=`pwd`

for GIT_DIR in `$DIR/git-dirs`
do
    cd $GIT_DIR
    echo  --- $GIT_DIR ---
    git status --porcelain
    git status | grep "Your branch is ahead of"
    cd $_PWD
done